spring:
  application:
    name: smc-service-registry

server:
  port: 3001

eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false  #no need close self protection default=true
    eviction-interval-timer-in-ms: 5000  #close interval(ms) default=60000ms
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      registerWithEureka: false
#      fetchRegistry: false

      
      